### ISSUE TITLE
Neurohub documentation display error (Firefox only)

### ISSUE THREAD

**Issue by prioux** [aces/cbrain-website#6]
Created originally by Alex Hutton in https://github.com/aces/cbrain/issues/1009 (which has been closed).

See the screenshot and description of the issue over there.

**Comment by candicecz** [comment]
Derek Lo worked on the neurohub website (can’t find his GitHub handle).

**Comment by prioux** [comment]
@candicecz Derek is @3design

**Comment by prioux** [comment]
I can confirm they are wrong in Firefox; also the first panel.

Also, the first of these panels still contain links to the old portal development site on port 5000, this need to be changed (discovered while looking at the logs for the placeholder site)

**Comment by prioux** [comment]
DARN IT, I made a mistake. This entire issue is actually about https://github.com/neurohub/neurohub.github.io , not the CBRAIN website.

I'm moving the entire discussion there.

**Comment by prioux** [comment]
I created two separate issues:

https://github.com/neurohub/neurohub.github.io/issues/18

and

https://github.com/neurohub/neurohub.github.io/issues/19
